Geo Bounding box
elarahq/es.query.builder pull request #15
Opened 2020-12-01 12:46 UTC by tavleenk13

2020-12-08 06:50 UTC, naveenkewalramani requested changes
update version as well

2020-12-08 06:50 UTC, naveenkewalramani commented on lib/misc/geo_bounding_box_point.rb
> +      pi = 3.14159
Math::PI

2020-12-08 06:50 UTC, naveenkewalramani commented on lib/misc/geo_bounding_box_point.rb
> +      radius_of_earth = 6378.1
constant

2020-12-08 12:16 UTC, naveenkewalramani approved these changes

2020-12-11 05:39 UTC, vgswn approved these changes

2020-12-11 06:28 UTC, SakshiJindal02 approved these changes

2020-12-11 06:28 UTC, merged